export const studentObj = {
  firstName: "",
  lastName: "",
  gender: "",
  dateOfBirth: "",
  roll: "",
  bloodGroup: "",
  religion: "",
  email: "",
  class: "",
  section: "",
  admissionId: "",
  phone: "",
};
export const studentInfo = [
  {
    status: "input",
    label: "First Name",
    type: "text",
    placeholder: "Enter First Name",
    name: "firstName",
    class: "input-field",
  },
  {
    status: "input",
    label: "Last Name",
    type: "text",
    placeholder: "Enter Last Name",
    name: "lastName",
    class: "input-field",
  },
  {
    status: "select",
    label: "Gender",
    name: "gender",
    value: ["Male", "Female"],
    class: "input-field",
  },
  {
    status: "input",
    label: "Date of Birth",
    type: "date",
    placeholder: "Enter DOB",
    name: "dateOfBirth",
    class: "input-field",
  },
  {
    status: "input",
    label: "Roll",
    type: "text",
    placeholder: "Enter Roll Number",
    name: "roll",
    class: "input-field",
  },
  {
    status: "select",
    label: "Blood Group",
    name: "bloodGroup",
    value: ["A-", "B+", "O+"],
    class: "input-field",
  },
  {
    status: "input",
    label: "Religion",
    type: "text",
    placeholder: "Enter Religion",
    name: "religion",
    class: "input-field",
  },
  {
    status: "input",
    label: "Email",
    type: "email",
    placeholder: "Enter Email",
    name: "email",
    class: "input-field",
  },
  // {
  //   status: "select",
  //   label: "Class",
  //   name: "class",
  //   value: [""],
  //   class: "input-field",
  // },
  // {
  //   status: "select",
  //   label: "Section",
  //   name: "section",
  //   value: [""],
  //   class: "input-field",
  // },
  {
    status: "input",
    label: "Admission Id",
    type: "text",
    placeholder: "Enter Admission Id",
    name: "admissionId",
    class: "input-field",
  },
  {
    status: "input",
    label: "Phone",
    type: "tel",
    placeholder: "Enter Phone",
    name: "phone",
    class: "input-field",
  },
];
