const GET_CLASSES = "GETCLASSES";
const GET_SECTIONS = "GETSECTIONS";
const GET_STUDENTS = "GETSTUDENTS";
const GET_TEACHERS = "GETTEACHERS";
const GET_ATTENDANCE = "GETATTENDANCE";
const GET_PARENTS = "GETPARENTS";

export {
  GET_CLASSES,
  GET_SECTIONS,
  GET_STUDENTS,
  GET_TEACHERS,
  GET_ATTENDANCE,
  GET_PARENTS,
};
