const FETCH_CLASSES_REQUEST = "FETCH_CLASSES_REQUEST";
const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS";
const FETCH_CLASSES_FAILURE = "FETCH_CLASSES_FAILURE";

const FETCH_SECTIONS_REQUEST = "FETCH_SECTIONS_REQUEST";
const FETCH_SECTIONS_SUCCESS = "FETCH_SECTIONS_SUCCESS";
const FETCH_SECTIONS_FAILURE = "FETCH_SECTIONS_FAILURE";

export {
  FETCH_CLASSES_REQUEST,
  FETCH_CLASSES_SUCCESS,
  FETCH_CLASSES_FAILURE,
  FETCH_SECTIONS_REQUEST,
  FETCH_SECTIONS_SUCCESS,
  FETCH_SECTIONS_FAILURE,
};
